name: "Draw Yu-Gi-Oh! Card"
description: "Draw Yu-Gi-Oh! Card on GitHub issue."
branding:
  icon: book
  color: gray-dark
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
runs:
  using: "node18"
  main: "dist/index.js"
